import { SUPPORT_PATH } from './about/story.js';
import { NEWS_PATH } from './announcements/views.js';
import { viewFor } from './courses/views.js';
import { CALENDAR_PATH } from './current-families/section.js';
import { STAFF_PATH } from './people/views.js';
import { POLICIES_PATH } from './policies/views.js';
import { PUBLIC_ROUTES } from './routes.js';

/** The full descriptions view's address, read from the one place it is written. */
const DESCRIPTIONS_PATH = viewFor('full-descriptions').path;

/**
 * The 301 map: where every URL the Wix site published lands on this one (#30).
 *
 * The full table of the nineteen live URLs is in `docs/mirror/README.md`, and
 * this is the half of it that can be honoured today — a redirect is only worth
 * having if what it points at exists, and a 301 to a 404 is strictly worse than
 * the 404 it replaces, because a crawler retires the old address on the
 * strength of it. Entries are added here as the pages they point at are built;
 * the test beside this file refuses a destination that is not an enumerated
 * public route, so the two lists cannot drift.
 *
 * What is still owed is `STILL_OWED` below, not a sentence in this comment: the
 * test reads it, so the list cannot quietly disagree with the map.
 *
 * `301` and not `302` deliberately: these addresses are not coming back, and a
 * permanent redirect is what moves whatever ranking the old page holds. `/` is
 * absent because it does not move — the same path serves the same purpose on
 * the new site.
 *
 * A second kind of entry lives here too, and is marked `this-site`: an address
 * **this** build published and has since moved, because the information
 * architecture was settled after four of these pages had already shipped. Those
 * are not in the mirror and must not be checked against it, but they are 301s
 * for the same reason — somebody has the link.
 */
export type Redirect = {
  /** The path being redirected, exactly as it was published. */
  from: string;
  /**
   * A path on this site, which must be an enumerated public route. May carry a
   * fragment, when the old address was a whole page of one idea.
   */
  to: string;
  /** Why this destination, for whoever reads the map next. */
  because: string;
  /**
   * Who published `from` — the Wix site, or an earlier version of this one.
   *
   * The test uses it: a `wix` entry has to appear in the mirror's own table of
   * the nineteen live URLs, which is what stops somebody adding a redirect for
   * an address that never existed. A `this-site` entry cannot be there by
   * definition.
   */
  origin: 'wix' | 'this-site';
};

/**
 * The published addresses that have nowhere to go yet, each blocked on the page
 * it should land on.
 *
 * Enumerated rather than described, because #30 AC 4 is "all 19 old URLs 301 to
 * a live page; none 404s" and the test measures the gap against this list. An
 * entry is deleted the moment its destination is built; when this is empty the
 * criterion is met, and the test says so in those words.
 *
 * It is empty. Every one of the nineteen is either served at the same path or
 * redirected, and the test enforces that against the mirror's own table rather
 * than against this sentence.
 *
 * A redirect is deliberately *not* added early. A 301 into a 404 retires the
 * old address on a promise the site cannot keep, which is strictly worse than
 * the 404 it replaces.
 */
export const STILL_OWED: readonly string[] = [];

export const REDIRECTS: readonly Redirect[] = [
  {
    from: '/statement-of-faith',
    to: '/about/beliefs',
    because:
      'The same document, now a real page under About. It is the one Wix address a family is ' +
      'most likely to have been sent directly, since applying is gated on reading it.',
    origin: 'wix',
  },
  {
    from: '/core-values',
    to: '/about',
    because:
      'The Method, the Core Values and the Mission & Vision were this one page, reached from the ' +
      'old About twice. About is now the page that carries them, in the same order.',
    origin: 'wix',
  },
  {
    from: '/about-1',
    to: '/about#location',
    because:
      'A whole Wix page for the building. It is a section of About now, and the fragment lands ' +
      'on it rather than making somebody hunt for the address they were looking for.',
    origin: 'wix',
  },
  {
    from: '/general-8',
    to: '/about#name',
    because:
      'The essay on where the name comes from, at an autogenerated slug nobody could have typed ' +
      'on purpose. Same text, on About, under a heading that says what it is.',
    origin: 'wix',
  },
  {
    from: '/about-3',
    to: '/admissions',
    because:
      'A whole Wix page carrying one sentence: the start date. That date is a field on the ' +
      'school details row now, printed on Admissions beside everything else a family needs ' +
      'before applying, so this lands there rather than at a page of its own.',
    origin: 'wix',
  },
  {
    from: '/giving',
    to: SUPPORT_PATH,
    because:
      'The giving explanation is the first half of that page, with the Give link read from the ' +
      'school details row rather than pasted, so it can move to the school’s own account.',
    origin: 'wix',
  },
  {
    from: '/volunteer',
    to: `${SUPPORT_PATH}#volunteer`,
    because:
      'The volunteer ask is the second half of that page, and the form is on it rather than on ' +
      'a Google Form on another domain. The fragment lands on the form itself.',
    origin: 'wix',
  },
  {
    from: '/about-5',
    to: `${SUPPORT_PATH}#volunteer`,
    because:
      'Byte-for-byte the same page as /volunteer, labeled "Media" in the old nav and holding ' +
      'no media at all. Same destination as the page it duplicates.',
    origin: 'wix',
  },
  {
    from: '/calendars-and-events',
    to: CALENDAR_PATH,
    because:
      'The calendar itself (#23) — the same four day tracks the old page linked five PDFs of, ' +
      'computed rather than retyped, with the year’s one-off events under it. Until #23 this ' +
      'landed on a section of Current Families that said the dates were not here yet.',
    origin: 'wix',
  },
  {
    from: '/download-calendars',
    to: CALENDAR_PATH,
    because:
      'The same page. That was six PDFs — a full sheet, one per day track, and the daily course ' +
      'offerings — and the calendar page replaces them with one generated file and a year that ' +
      'prints as a dated list. The dates a course meets on are on the course’s own page (#237).',
    origin: 'wix',
  },
  {
    from: '/courses',
    to: '/classes',
    because:
      'The old courses page was a link hub with no content of its own. Its three destinations ' +
      'are the three renderings, and By Age is the one that lands.',
    origin: 'wix',
  },
  {
    from: '/courses-by-grade-level',
    to: '/classes',
    because:
      'One-to-one with the By Age view. Ages are the primary axis here, as they are in the ' +
      'school’s own course data; the old page approximated them as grades.',
    origin: 'wix',
  },
  {
    from: '/daily-course-offerings',
    to: '/classes/by-day',
    because: 'One-to-one with the timetable, which is what that page was.',
    origin: 'wix',
  },
  {
    from: '/full-course-descriptions',
    to: DESCRIPTIONS_PATH,
    because: 'One-to-one with the full descriptions.',
    origin: 'wix',
  },
  {
    from: '/classes/full-descriptions',
    to: DESCRIPTIONS_PATH,
    because:
      'This build published that address before #9’s tree was applied to it. The word "full" ' +
      'only ever distinguished the page from the Wix course list, which no longer exists.',
    origin: 'this-site',
  },
  {
    from: '/team-4',
    to: STAFF_PATH,
    because:
      'The three bios that page carried are on the staff page, alongside every instructor the ' +
      'catalog names.',
    origin: 'wix',
  },
  {
    from: '/staff',
    to: STAFF_PATH,
    because:
      'This build published the staff page at the root before #9’s tree was applied. Who ' +
      'teaches here is an About question, and the tree files it under About.',
    origin: 'this-site',
  },
  {
    from: '/special-announcement',
    to: NEWS_PATH,
    because:
      'The Weis Markets fundraiser was a page in a fixed slot. It is an announcement here, and ' +
      'the news page is where it and every fundraiser after it lives.',
    origin: 'wix',
  },
  {
    from: '/news',
    to: NEWS_PATH,
    because:
      'This build published news at the root before #9’s tree was applied. News is for the ' +
      'families already here, which is what the Current Families section means.',
    origin: 'this-site',
  },
  {
    from: '/policies',
    to: POLICIES_PATH,
    because:
      'The listing page moved under Current Families with the rest of what a current family ' +
      'needs. The Wix site published this address and so did this one, and the policy files ' +
      'themselves did not move at all — /policies/<slug>.pdf is printed on a handbook.',
    origin: 'wix',
  },
];

/** The map in the shape Astro's `redirects` config wants. */
export function redirectConfig(
  redirects: readonly Redirect[] = REDIRECTS,
): Record<string, { status: 301; destination: string }> {
  return Object.fromEntries(
    redirects.map(({ from, to }) => [from, { status: 301 as const, destination: to }]),
  );
}

/** The paths this site would serve a redirect for. */
export function redirectedPaths(redirects: readonly Redirect[] = REDIRECTS): string[] {
  return redirects.map((redirect) => redirect.from);
}

/**
 * Whether a destination is somewhere this site actually renders.
 *
 * A destination may carry a fragment. Three of the Wix addresses were whole
 * pages of one idea each — Location, Pharos Meaning — and they now land on a
 * section of `/about`; sending somebody who bookmarked "Location" to the top of
 * a six-section page and letting them hunt is a worse migration than the 404.
 * Only the path part is checked against the route list, because the fragment is
 * an anchor in a template rather than a route.
 */
export function isLiveDestination(path: string): boolean {
  const [routePath] = path.split('#');
  return PUBLIC_ROUTES.some((route) => route.path === routePath);
}
