import base64, io, json
from PIL import Image, ImageOps, ImageChops

SRC = r"C:\Users\wyatt\source\repos\pharos-academy-site\docs\mirror\assets"
out = {}

def enc(img, fmt, **kw):
    buf = io.BytesIO()
    img.save(buf, fmt, **kw)
    b = buf.getvalue()
    mime = {"WEBP": "image/webp", "PNG": "image/png", "JPEG": "image/jpeg"}[fmt]
    return f"data:{mime};base64,{base64.b64encode(b).decode()}", len(b)

# --- 1. the Pharos of Alexandria engraving ---
eng = Image.open(SRC + r"\cecb9d_46661c373a624be8a682d16ef80e5074~mv2.png").convert("L")
eng = eng.resize((1200, int(1200 * eng.height / eng.width)), Image.LANCZOS)
# light-ground version: plain grayscale
d, n = enc(eng.convert("RGB"), "WEBP", quality=72, method=6)
out["engraving_light"] = d
print("engraving_light", n // 1024, "KB")
# dark-ground version: ink becomes alpha, RGB flat white -> tint with CSS via opacity/blend
alpha = ImageChops.invert(eng)
alpha = alpha.point(lambda v: min(255, int(v * 1.35)))
ink = Image.new("RGBA", eng.size, (255, 255, 255, 0))
ink.putalpha(alpha)
d, n = enc(ink, "WEBP", quality=70, method=6)
out["engraving_ink"] = d
print("engraving_ink", n // 1024, "KB")
# mask version for variant D: the scan's ground is ~215-234, not white, so a
# multiply blend always leaves a faint rectangle. Drive the ground fully to
# zero alpha instead and use the result as a CSS mask over a flat ink fill.
mask_a = eng.point(lambda v: 0 if v >= 200 else min(255, int((200 - v) * 255 / 150)))
mask = Image.new("RGBA", eng.size, (0, 0, 0, 0))
mask.putalpha(mask_a)
d, n = enc(mask, "PNG", optimize=True)
out["engraving_mask"] = d
print("engraving_mask", n // 1024, "KB", eng.size)

# --- 2. the existing lighthouse mark, background knocked out ---
logo = Image.open(SRC + r"\cecb9d_0ca6169ee8cf426fbc06471e38be23f4~mv2.jpg").convert("RGB")
px = logo.load()
rgba = Image.new("RGBA", logo.size)
rp = rgba.load()
for y in range(logo.height):
    for x in range(logo.width):
        r, g, b = px[x, y]
        m = min(r, g, b)
        a = 255 - m if m > 235 else 255
        if m > 235:
            a = int(max(0, (255 - m) / 20 * 255))
        rp[x, y] = (r, g, b, a)
bbox = rgba.split()[3].getbbox()
rgba = rgba.crop(bbox)
rgba = rgba.resize((480, int(480 * rgba.height / rgba.width)), Image.LANCZOS)
d, n = enc(rgba, "PNG", optimize=True)
out["mark"] = d
print("mark", n // 1024, "KB", rgba.size)

# --- 3. the church building (the only real, face-free school photo we hold) ---
ch = Image.open(SRC + r"\cecb9d_48e58079a244471aa233bc4d0110b4e2~mv2.webp").convert("RGB")
ch = ch.resize((900, int(900 * ch.height / ch.width)), Image.LANCZOS)
d, n = enc(ch, "WEBP", quality=68, method=6)
out["church"] = d
print("church", n // 1024, "KB")

# --- 4. the painterly still-lifes (variant E's imagery slots) ---
# Generated by the user, not by an agent here; provenance in assets/imagery/README.md.
# All are 16:9 as delivered. Four of them fill four of E's five slots; slot 4
# (staff portraits) is the only one left, and it needs photographs of real
# consenting adults, not a painting. NOTE: no people in any of them, which is
# what makes them usable at all.
STILLS = r"C:\Users\wyatt\source\repos\pharos-academy-site\assets\imagery"

def crop_to(im, ratio, bias=0.5):
    """Centre-crop to `ratio` (w/h). `bias` slides the kept window: 0 = keep the
    left/top edge, 1 = keep the right/bottom edge, .5 = dead centre."""
    w, h = im.size
    if w / h > ratio:                      # too wide: take width off the sides
        nw = round(h * ratio)
        x = round((w - nw) * bias)
        return im.crop((x, 0, x + nw, h))
    nh = round(w / ratio)                  # too tall: take height off top/bottom
    y = round((h - nh) * bias)
    return im.crop((0, y, w, y + nh))

# slot, source, target ratio (None = leave as delivered), crop bias.
#   still-desk: the left third is bare wall, so the 3:2 crop leans right to keep
#              the mug and the brush jar in frame.
#   vista-path: was 21:9, when it ran full-bleed across a band. E now sets it as
#              an accent beside a heading, about a 38% column, where a 21:9 frame
#              is a 180px sliver — so it takes the desk's 3:2 instead. Centred:
#              unlike the desk, nothing in this frame is off to one side.
STILL_SPECS = [
    ("still_scripture", "still-scripture.jpg", None, 0.5),
    ("still_desk",  "still-desk.png",  3 / 2,  0.70),
    ("vista_path",  "vista-path.png",  3 / 2,  0.50),
]
for key, name, ratio, bias in STILL_SPECS:
    im = Image.open(STILLS + "\\" + name).convert("RGB")
    if ratio:
        im = crop_to(im, ratio, bias)
    im = im.resize((1400, round(1400 * im.height / im.width)), Image.LANCZOS)
    d, n = enc(im, "WEBP", quality=76, method=6)
    out[key] = d
    print(key, n // 1024, "KB", im.size)

# --- 5. the four H.O.P.E. popout paintings -----------------------------------
# Generated by the user. THREE OF THESE FOUR CONTAIN PEOPLE, which every other
# image in this directory deliberately does not. The rule that forbade it was
# overruled by the owner on 2026-07-31 for this row only; the reversal and its
# reason are recorded in assets/imagery/README.md, and #13 carries it into the
# client conversation. Do not read this block as the rule having been relaxed
# generally — slot 4 still wants photographs of real consenting adults.
#
# These are popouts, not plates: the card is ~380 CSS px, so 800px at 2× is
# ample and a 1400px rendition would be four times the bytes for nothing. 16:9
# as delivered, cropped to 3:2 dead centre — every one of them is composed with
# its subject in the middle, so no bias is needed.
HOPE_SPECS = [
    ("hope_h", "hope-h-helping.png"),
    ("hope_o", "hope-o-our.png"),
    ("hope_p", "hope-p-parents.png"),
    ("hope_e", "hope-e-educate.png"),
]
for key, name in HOPE_SPECS:
    im = Image.open(STILLS + "\\" + name).convert("RGB")
    im = crop_to(im, 3 / 2, 0.5)
    im = im.resize((800, round(800 * im.height / im.width)), Image.LANCZOS)
    d, n = enc(im, "WEBP", quality=74, method=6)
    out[key] = d
    print(key, n // 1024, "KB", im.size)

# still-study.png and still-library.png are both in the repo and both unused. They
# are the two academic plates — books, a globe, a brass compass, a portico drawing —
# and they are near-identical to each other, so only one could ever have run. Slot 3
# then went to still-scripture.jpg on the owner's instruction, which displaced the
# survivor too. Held in reserve for an interior page.

json.dump(out, open("assets.json", "w"))
print("total json", len(json.dumps(out)) // 1024, "KB")
